# Site settings
name: More hunger
email: splinfengwang@gmail.com
author: 王林峰
url: 
resume_site: 
github: https://github.com/splinfengwang
baseurl: ""
description: 我的前端学习笔记。
meta_description: 王林峰;个人博客
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: splinfengwang
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : 
    duoshuo:
        short_name : 
    disqus :
        short_name : 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light